# Vagrantfile for multi-VM setup with two Ubuntu Focal 64 machines

Vagrant.configure("2") do |config|
  # Define the base box
  config.vm.box = "ubuntu/focal64"

  # VM1 configuration
  config.vm.define "master" do |vm1|
    vm1.vm.hostname = "vm1"
    vm1.vm.network "public_network"
    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = "2000"
      vb.cpus = 2
    end
      vm1.vm.provision "shell", path:"./install-jenkins.sh"
  end

  # VM2 configuration
  config.vm.define "slave1" do |vm2|
    vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", ip: "192.168.50.3"
    vm2.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "1000"
      vb.cpus = 1
    end
     vm2.vm.provision "shell", path:"./install-docker.sh"
  end
end
