Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Jenkins Master (lightweight)
  config.vm.define "master" do |vm1|
    vm1.vm.hostname = "jenkins-master"
    vm1.vm.network "public_network"
    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = "1200"
      vb.cpus = 6
    end
    vm1.vm.provision "shell", path: "./install-jenkins.sh"
  end

  # Staging Node App + SonarQube (optimized)
  config.vm.define "slave1" do |vm2|
    vm2.vm.hostname = "staging-node"
    vm2.vm.network "private_network", ip: "192.168.50.3"
    vm2.vm.provider "virtualbox" do |vb|
      vb.memory = "3072"  
      vb.cpus = 4
    end
    vm2.vm.provision "shell", path: "./setupStaging.sh"
  end

  # Docker Swarm Manager + Registry
  config.vm.define "docker" do |vm3|
    vm3.vm.hostname = "swarm-manager"
    vm3.vm.network "private_network", ip: "192.168.50.4"
    vm3.vm.network "forwarded_port", guest: 5050, host: 5050 #backend
    vm3.vm.network "forwarded_port", guest: 5173, host: 5173 #frontend
    vm3.vm.network "forwarded_port", guest: 9090, host: 9090#prometheus
    vm3.vm.network "forwarded_port", guest: 3000, host: 3000#graphana
    vm3.vm.provider "virtualbox" do |vb|
      vb.memory = "3048"  
      vb.cpus = 6
    end
    vm3.vm.provision "shell", path: "./start-registry.sh"
  end

  # Swarm Worker 1
  config.vm.define "swarm1" do |vm4|
    vm4.vm.hostname = "swarm-worker-1"
    vm4.vm.network "private_network", ip: "192.168.50.5"
    vm4.vm.provider "virtualbox" do |vb|
      vb.memory = "1100"
      vb.cpus = 4
    end
    vm4.vm.provision "shell", path: "./install-docker.sh"
  end

  # Swarm Worker 2
  config.vm.define "swarm2" do |vm5|
    vm5.vm.hostname = "swarm-worker-2"
    vm5.vm.network "private_network", ip: "192.168.50.6"     
    vm5.vm.provider "virtualbox" do |vb|
      vb.memory = "1100"
      vb.cpus = 4
    end
    vm5.vm.provision "shell", path: "./install-docker.sh"
  end
end
